---
spring.main:
  banner-mode: OFF
  cloud-platform: NONE

server:
  shutdown: GRACEFUL
  #forward-headers-strategy: NONE

  # Based on AWS ALB's
  # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html
  netty.max-initial-line-length: 16KB
  max-http-request-header-size: 64KB # The maximum length of all headers.

  # Prevent usage by default
  reactive.session:
    max-sessions: 1
    timeout: 1ms


logging.config: classpath:logback-main.xml
logging.level:
  ROOT: INFO
  io.syscall: DEBUG

  "io.netty.buffer.ByteBufUtil": DEBUG

  # Default Epoll support : false
  "reactor.netty.resources": DEBUG

  ## Using candidate component class from index: ${BEAN FQCN}
  #"org.springframework.context.annotation.ClassPathBeanDefinitionScanner": DEBUG

  # For monitoring
  #  "Application availability state LivenessState changed to CORRECT"
  #  "Application availability state ReadinessState changed to ACCEPTING_TRAFFIC"
  "org.springframework.boot.availability.ApplicationAvailabilityBean": DEBUG

  # BeanFactory id=${UUID}
  "org.springframework.cloud.context.scope.GenericScope": WARN

  # ControllerAdvice beans: 0 @ModelAttribute, 0 @InitBinder, 1 @ExceptionHandler
  "org.springframework.web.reactive.result.method.annotation.ControllerMethodResolver": DEBUG

spring.jmx.enabled: true
spring.application.admin.enabled: true

management.endpoints:
  access.default: NONE
  jmx:
    exposure.include: "*"
  web:
    base-path: /internal
    discovery.enabled: false
    exposure.include: []
    exposure.exclude: "*"
management.endpoint:
  # Explicitly Disabled
  heapdump.access: NONE
  threaddump.access: NONE
  shutdown.access: NONE
  beans.access: UNRESTRICTED
  mappings.access: UNRESTRICTED
  configprops.access: UNRESTRICTED
  configprops.show-values: ALWAYS
  env.access: UNRESTRICTED
  env.show-values: ALWAYS

management.server:
  add-application-context-header: true

management.tracing:
  propagation.consume: [ W3C ]

management.cloudfoundry.enabled: false

spring.autoconfigure.exclude:
  - org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.context.ShutdownEndpointAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.management.HeapDumpWebEndpointAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.management.ThreadDumpEndpointAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.logging.LogFileWebEndpointAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.logging.LoggersEndpointAutoConfiguration
  - org.springframework.cloud.autoconfigure.WritableEnvironmentEndpointAutoConfiguration

  - org.springframework.boot.health.autoconfigure.actuate.endpoint.HealthEndpointAutoConfiguration
  - org.springframework.boot.health.autoconfigure.contributor.HealthContributorAutoConfiguration
  - org.springframework.boot.health.autoconfigure.registry.HealthContributorRegistryAutoConfiguration
  - org.springframework.boot.health.autoconfigure.application.AvailabilityHealthContributorAutoConfiguration
  - org.springframework.boot.health.autoconfigure.application.DiskSpaceHealthContributorAutoConfiguration
  - org.springframework.boot.health.autoconfigure.application.SslHealthContributorAutoConfiguration

  - org.springframework.boot.micrometer.metrics.autoconfigure.export.otlp.OtlpMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.simple.SimpleMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.prometheus.PrometheusMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.appoptics.AppOpticsMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.atlas.AtlasMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.datadog.DatadogMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.dynatrace.DynatraceMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.elastic.ElasticMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.ganglia.GangliaMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.graphite.GraphiteMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.humio.HumioMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.influx.InfluxMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.kairos.KairosMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.newrelic.NewRelicMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.stackdriver.StackdriverMetricsExportAutoConfiguration
  - org.springframework.boot.micrometer.metrics.autoconfigure.export.statsd.StatsdMetricsExportAutoConfiguration
