---
spring.application.name: apiserver

logging.level: { }

server:
  shutdown: GRACEFUL
  forward-headers-strategy: NATIVE

  # Based on AWS ALB's
  # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html
  netty.max-initial-line-length: 16KB
  max-http-request-header-size: 64KB # The maximum length of all headers.



---
spring.config.activate.on-profile: local

custom.netty.webserver:
  use-virtual-thread: false
