# https://opentelemetry.io/docs/zero-code/java/agent/configuration/
# Note: Must set -Dotel.javaagent.configuration-file=<this file path>

otel.javaagent.logging=application

otel.instrumentation.logback-appender.experimental.capture-marker-attribute=true
otel.instrumentation.logback-appender.experimental.capture-key-value-pair-attributes=true
otel.instrumentation.logback-appender.experimental.capture-mdc-attributes=*

otel.propagators=tracecontext

otel.instrumentation.http.server.capture-request-headers=Accept,Accept-Encoding,Accept-Language,Alt-Used,Cache-Control,Content-Digest,Content-Language,Content-Type,Expect,Forwarded,Host,Idempotency-Key,If-Match,If-Modified-Since,If-None-Match,If-Unmodified-Since,Origin,Referer,Sec-CH-Arch,Sec-CH-Mobile,Sec-CH-Model,Sec-CH-Platform,Sec-CH-UA,Sec-CH-UA-Platform-Version,Sec-Fetch-Dest,Sec-Fetch-Mode,Sec-Fetch-Site,Sec-Fetch-User,Sec-Purpose,Service-Worker,Via,X-Client-Request-Id,X-Forwarded-For,X-Forwarded-Host,X-Forwarded-Proto,X-Request-Id
otel.instrumentation.http.server.capture-response-headers=Accept,Authentication-Control,Cache-Control,Content-Digest,Content-Disposition,Content-Language,Content-Location,Content-Type,ETag,Last-Modified,Link,Location,Retry-After,WWW-Authenticate,X-Request-Id
otel.instrumentation.http.client.capture-request-headers=Accept,Accept-Encoding,Accept-Language,Alt-Used,Cache-Control,Content-Digest,Content-Language,Content-Type,Expect,Forwarded,Host,Idempotency-Key,If-Match,If-Modified-Since,If-None-Match,If-Unmodified-Since,Origin,Referer,User-Agent,Via,X-Client-Request-Id,X-Forwarded-For,X-Forwarded-Host,X-Forwarded-Proto,X-Request-Id
otel.instrumentation.http.client.capture-response-headers=Accept,Age,Allow,Authentication-Control,Cache-Control,Content-Digest,Content-Disposition,Content-Language,Content-Location,Content-Type,ETag,Last-Modified,Link,Location,Proxy-Authenticate,Retry-After,Server,WWW-Authenticate,X-Request-Id

otel.instrumentation.common.experimental.controller-telemetry.enabled=true
