# https://docs.gradle.org/8.0.2/userguide/platforms.html#sub::toml-dependencies-format
[metadata]
format.version = "1.1"

[versions]
kotlin = "1.8.22"
junit = "5.9.2"
spring-boot = "3.1.1"
spotless = "6.19.0"

[libraries]
gradlePlugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-springBoot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
gradlePlugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

bom-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
bom-junit = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
bom-springBoot = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

assertj = { group = "org.assertj", name = "assertj-core", version = "3.24.2" }

[bundles]
bomDependencies = [
  # kotlin은 별도 지정
  "bom-junit",
  "bom-springBoot",
]

dependencies = [
  "assertj",
]

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
