# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: "Validate Gradle Wrapper"

on:
  push:
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'
  pull_request:
    paths:
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'

jobs:
  # https://github.com/gradle/wrapper-validation-action
  # https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/6f09cf79b1a18850e88897a54c1e39ef167b803a/.github/workflows/build-common.yml#L49C1-L55C54
  gradle-wrapper-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
